package ui;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

import main.mainpage;

public class TimesheetUI extends javax.swing.JDialog {

	boolean addRecord = false;

	private void clearInputBoxes() {
		txtNumber.setText("");
		txtNumber.setEnabled(true);
		txtName.setText("");
		desc.setText("");
		hour.setText("");
		txtAddress1.setText("");
		txtAddress2.setText("");
		offeredSP.setText("");
		offeredSU.setText("");
		teachers.setText("");
		preReqs.setText("");

	}

	/*private int addNew() throws SQLException {
		CourseRegister newObj = CourseRegister.getInstance();
		newObj.addCourse(txtNumber.getText(), txtName.getText(),
				desc.getText(), hour.getText(), txtAddress1.getText(),
				txtAddress2.getText(), offeredSP.getText(), offeredSU.getText(),
				preReqs.getText(), teachers.getText());
		return 1;
	}

	private boolean updateRecord() throws SQLException {
		CourseRegister newObj = CourseRegister.getInstance();
		boolean bool = newObj.editCourse(txtNumber.getText(),
				txtName.getText(), desc.getText(), hour.getText(),
				txtAddress1.getText(), txtAddress2.getText(), offeredSP.getText(),
				offeredSU.getText(), preReqs.getText(), teachers.getText());

		return bool;
	}

	private boolean deleteRecord() throws SQLException {
		CourseRegister newObj = CourseRegister.getInstance();
		boolean bool = newObj.deleteCourse(txtNumber.getText());

		return bool;
	}
*/
	private void loadRecords() {

		/*List<Course> courseList = CourseRegister.courses;
		CourseTableModel tableModel = new CourseTableModel(courseList);
		jTable1.setModel(tableModel);*/

		jTable1.getSelectionModel().addListSelectionListener(
				new ListSelectionListener() {
					public void valueChanged(ListSelectionEvent event) {
						try {
							if (jTable1.getSelectedRow() >= 0) {
								txtNumber.setEnabled(false);
								// String
								// code,name,desc,hour,txtAddress1,txtAddress2,offeredSP,offeredSU;
								Object codeV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 0);
								Object nameV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 1);
								Object descV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 2);
								Object hourV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 3);
								Object txtAddress1V = jTable1.getValueAt(
										jTable1.getSelectedRow(), 4);
								Object txtAddress2V = jTable1.getValueAt(
										jTable1.getSelectedRow(), 5);
								Object offeredSPV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 6);
								Object offeredSUV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 7);
								Object preReqsV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 8);
								Object teachersV = jTable1.getValueAt(
										jTable1.getSelectedRow(), 9);

								txtNumber.setText(codeV.toString());
								txtName.setText(nameV.toString());
								desc.setText(descV.toString());
								hour.setText(hourV.toString());
								txtAddress1.setText(txtAddress1V.toString());
								txtAddress2.setText(txtAddress2V.toString());
								offeredSP.setText(offeredSPV.toString());
								offeredSU.setText(offeredSUV.toString());
								preReqs.setText(preReqsV.toString());
								teachers.setText(teachersV.toString());
							}
						} catch (Exception ex) {
							System.out.println(ex.getMessage());
						}
					}
				});

		

		DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
		rightRenderer.setHorizontalAlignment(SwingConstants.LEFT);
		jTable1.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
	}

	/**
	 * Creates new form FORMEmployees
	 */
	public TimesheetUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel1.setSize(700, 700);
		jLabelNumber = new javax.swing.JLabel();
		txtNumber = new javax.swing.JTextField();
		jLabelName = new javax.swing.JLabel();
		txtName = new javax.swing.JTextField();
		jLabelAddress1 = new javax.swing.JLabel();
		desc = new javax.swing.JTextField();
		jLabelAddress2 = new javax.swing.JLabel();
		hour = new javax.swing.JTextField();
		jLabelCity = new javax.swing.JLabel();
		txtAddress1 = new javax.swing.JTextField();
		jLabelState = new javax.swing.JLabel();
		txtAddress2 = new javax.swing.JTextField();
		jLabelZip = new javax.swing.JLabel();
		offeredSP = new javax.swing.JTextField();
		jLabelEmail = new javax.swing.JLabel();
		offeredSU = new javax.swing.JTextField();
		jLabelContact = new javax.swing.JLabel();
		teachers = new javax.swing.JTextField();
		jLabelInvoiceFreq = new javax.swing.JLabel();
		preReqs = new javax.swing.JTextField();
		btnAddNew = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();
		btnDelete = new javax.swing.JButton();
		btnPrintAll = new javax.swing.JButton();
		btnClose = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Course Records Editor",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 1, 11))); // NOI18N

		jLabelNumber.setText("Course Code:");

		txtNumber.setEnabled(false);

		jLabelName.setText("Course Name:");

		jLabelAddress1.setText("Desc:");

		// desc.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		// "Male", "Female" }));

		jLabelAddress2.setText("Hour :");
		jLabelCity.setText("txtAddress1 :");
		jLabelState.setText("txtAddress2:");

		jLabelZip.setText("OfferedSP :");
		jLabelEmail.setText("OfferedSU :");
		jLabelContact.setText("Teachers :");
		jLabelInvoiceFreq.setText("Pre Req :");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelContact)
														.addComponent(jLabelZip)
														.addComponent(jLabelCity)
														.addComponent(jLabelAddress1)
														.addComponent(jLabelName)
														.addComponent(jLabelNumber))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								teachers,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								120,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								offeredSP,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								83,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtAddress1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								83,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								desc,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								120,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtName,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								200,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtNumber,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								100,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabelInvoiceFreq,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabelEmail,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabelState,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabelAddress2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								hour,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								57,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtAddress2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								57,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								offeredSU,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								57,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								preReqs,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								57,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabelState,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabelAddress2)

																		/*
																		 * .
																		 * addComponent
																		 * (
																		 * offeredSP
																		 * ) .
																		 * addComponent
																		 * (
																		 * offeredSU
																		 * ) .
																		 * addComponent
																		 * (
																		 * teachers
																		 * )
																		 */)
														// .addComponent(txtName)
														)).addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelNumber)
														.addComponent(
																txtNumber,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelName)
														.addComponent(
																txtName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelAddress1)
														.addComponent(
																desc,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelAddress2)
														.addComponent(
																hour,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabelState)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabelCity)
																		.addComponent(
																				txtAddress1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				txtAddress2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelEmail)
														.addComponent(
																offeredSU,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelZip)
														.addComponent(
																offeredSP,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelContact)
														.addComponent(
																teachers,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelInvoiceFreq)
														.addComponent(
																preReqs,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		btnAddNew.setText("Add New");
		btnAddNew.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddNewActionPerformed(evt);
			}
		});

		btnUpdate.setText("Update");
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});

		btnDelete.setText("Delete");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		btnPrintAll.setText("Print All");
		btnPrintAll.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPrintAllActionPerformed(evt);
			}
		});

		btnClose.setText("Close");
		btnClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCloseActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { {}, {}, {}, {} }, new String[] {

				}));
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btnAddNew)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btnUpdate)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		btnDelete)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnPrintAll)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		90,
																		Short.MAX_VALUE)
																.addComponent(
																		btnClose))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(5, 5, 5)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		0,
																		Short.MAX_VALUE))
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										101,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnAddNew)
												.addComponent(btnUpdate)
												.addComponent(btnDelete)
												.addComponent(btnPrintAll)
												.addComponent(btnClose))
								.addContainerGap(21, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void formWindowOpened(java.awt.event.WindowEvent evt) {

		loadRecords();

	}

	private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {
		addRecord = true;

		clearInputBoxes();

		txtName.requestFocus();
	}

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
		mainpage x = new mainpage();

		getContentPane().getParent().getParent().getParent().setVisible(false);
		// getContentPane().getParent().removeAll();
		x.main(null);
		// System.exit(1);
	}

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		int dialogResult = JOptionPane.showConfirmDialog(null,
				"Are you sure you want to delete this record?",
				"Confirm Delete Record?", JOptionPane.YES_NO_OPTION);

		if (dialogResult == JOptionPane.YES_OPTION) {
			try {
				boolean ret = true;//deleteRecord();
				String message = "";
				if (ret) {
					message = " Record deleted";
				} else
					message = " Record failed to delete";
				JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
						JOptionPane.INFORMATION_MESSAGE);
				loadRecords();
			} catch (Exception ex) {
				System.out.println(ex.getMessage());
			}
		}
	}

	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {
		int dialogResult = JOptionPane.showConfirmDialog(null,
				"Are you sure you want to update this record?",
				"Confirm Update Record?", JOptionPane.YES_NO_OPTION);

		if (dialogResult == JOptionPane.YES_OPTION) {
			try {
				if (addRecord == true) {
					int ret =1;// addNew();
					if (ret == 1) {
						String message = " Record added.";
						JOptionPane.showMessageDialog(new JFrame(), message,
								"Dialog", JOptionPane.INFORMATION_MESSAGE);
					}
				} else {
					boolean ret = true;//updateRecord();
					String message = "";
					if (ret) {
						message = " Record updated";
					} else
						message = " Record failed to update";
					JOptionPane.showMessageDialog(new JFrame(), message,
							"Dialog", JOptionPane.INFORMATION_MESSAGE);

				}

				addRecord = false;
				loadRecords();
			} catch (Exception ex) {
				System.out.println(ex.getMessage());
			}
		}
	}

	private void btnPrintAllActionPerformed(java.awt.event.ActionEvent evt) {
		// DisplayReports displayReports = new DisplayReports();

		// displayReports.showEmployees();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ClientUI dialog = new ClientUI(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnAddNew;
	private javax.swing.JButton btnClose;
	private javax.swing.JButton btnDelete;
	private javax.swing.JButton btnPrintAll;
	private javax.swing.JButton btnUpdate;
	private javax.swing.JTextField desc;
	private javax.swing.JLabel jLabelNumber;
	private javax.swing.JLabel jLabelName;
	private javax.swing.JLabel jLabelAddress1;
	private javax.swing.JLabel jLabelAddress2;
	private javax.swing.JLabel jLabelCity;
	private javax.swing.JLabel jLabelState;
	private javax.swing.JLabel jLabelZip;
	private javax.swing.JLabel jLabelEmail;
	private javax.swing.JLabel jLabelContact;
	private javax.swing.JLabel jLabelInvoiceFreq;
	private javax.swing.JLabel jLabelBillingTerm;
	private javax.swing.JLabel jLabelInvoiceGrouping;
	private javax.swing.JLabel jLabelStatus;
	
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField hour;
	private javax.swing.JTextField txtNumber;
	private javax.swing.JTextField txtName;
	private javax.swing.JTextField txtAddress1;
	private javax.swing.JTextField txtAddress2;
	private javax.swing.JTextField offeredSP;
	private javax.swing.JTextField offeredSU;
	private javax.swing.JTextField teachers;
	private javax.swing.JTextField preReqs;
	// End of variables declaration

}
